### PR TITLE
Bump the build to add Python 3.7 support

### PR DESCRIPTION
**Pull request by mrterry**
I think this is how to do it.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrterry** [comment]
@conda-forge-admin, please rerender

**Comment by mariusvniekerk** [comment]
This is already a noarch:python  package so nothing needs to be done.

**Comment by mrterry** [comment]
I think you still need to have a python 3.7 build.  For the following `environment.yml` file I get an `UnsatisfiableError`

```
name: pgcli
channels:
- conda-forge
dependencies:

- python=3.7
- pgcli
```

```
$ conda env create -n pgcli -f pgcli.yml
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - pgcli -> pgspecial[version='>=1.8.0'] -> python[version='>=3.6,<3.7.0a0']
  - python=3.7
Use "conda info <package>" to see the dependencies for each package.
```

Now that I paste the error message.  Perhaps the issue is with `pgspecial`?

**Comment by mariusvniekerk** [comment]
The issue is that you are lacking a pgspecial for python3.7

**Comment by mariusvniekerk** [comment]
So i've rebuilt pgspecial and pgcli for newer versions.  so this should not be needed anymore

**Pull request closed without merging**
